services:
  vote:
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 1

  worker:
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  result:
    depends_on:
      db:
        condition: service_healthy
    deploy:
      replicas: 1

networks:
  voting:
    driver: bridge
    name: swarm-voting-local